### ISSUE TITLE
Don't create multiple layers

### ISSUE THREAD

**Issue by yoshi1125hisa** [Senzing/docker-python-demo#30]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by docktermj** [comment]
Hi @yoshi1125hisa !

Thank you for your interest.  

You are correct in principle.   But there is an aspect of cache invalidation that you may not be aware of.   I first learned of this in the "The Docker Book"  (https://dockerbook.com/)  This is manifested in the use of `REFRESHED_AT`.

On the use of `FLASK_APP`  I'm caught between minimizing layers and clarity of code.   Everything after the comment

```console
# Runtime execution
```

pertains to the runtime environment and is a clear teaching tool.  Putting it in a layer above obfuscates the teaching value, even though it removes a layer.   So I'll have to think about that one.

I like your introduction of `FLASK_VER`.   It gives the user of the Dockerfile the ability to change versions of flask at `docker build` time without having to modify the Dockerfile.   As a "build time" variable,  would the use of `ARG` (vs.`ENV`) be more appropriate?  In either case,   I'll be adding your concept to the code.   Thank you!

**Comment by yoshi1125hisa** [comment]
Thank you for your reply @docktermj !

I first notice about your using of "REFRESHED_AT" and "caching" from your comments.
I also realized that I needed to think deeply about "Runtime execution".
So, you are correct and your code is better.

I use `ENV` when dealing with` FLASK_VER`.
Because it is an environment variable that is handled only in Dockerfile.
If you are using a version of Flask outside of a Dockerfile, ARG would be more appropriate.

I will delete the cache replacement.
Do you leave other code as they are?Or do you rewrite it yourself?

Thank you!

**Comment by docktermj** [comment]
@yoshi1125hisa I can write a new branch/pull request with your `FLASK_VER` idea.  I really like the idea.

Can you elaborate a little on `ARG` vs. `ENV`.   I'm not quite sure I understand your point of view.
I'm favoring `ARG` at `docker build` time as described in https://vsupalov.com/docker-arg-vs-env/

Is there as use of `FLASK_VER` in a running container?

**Comment by yoshi1125hisa** [comment]
@docktermj 
OK, thanx.

I just understand it.
`FLASK_VER` is not used in container.
So,  should use `ARG` .

This time, I'm sorry that wrong issue.

**Comment by yoshi1125hisa** [comment]
I closed #31 and open #34 .
Can you check this Pull request?
Thank you.

**Comment by docktermj** [comment]
#34 has been merged into master.   Thank you!!!!

**Comment by yoshi1125hisa** [comment]
Thank you too!
